cl AlgorithmEx.cpp /clr:safe
cl arraylist.cpp /clr:safe
cl bitarray.cpp /clr:safe
cl DequeEx.cpp /clr:safe
cl DictionaryGeneric.cpp /clr:safe
cl HashSortList.cpp /clr:safe
cl IEnum_foreach.cpp /clr:safe
cl LinkedListGeneric.cpp /clr:safe
cl ListDict.cpp /clr:safe
cl ListEx.cpp /clr:safe
cl ListGeneric.cpp /clr:safe
cl MapEx.cpp /clr:safe
cl NameValue.cpp /clr:safe
cl PriorityQueueAdptEx.cpp /clr:safe
cl QueueAdptEx.cpp /clr:safe
cl QueueStack.cpp /clr:safe
cl QueueStackGeneric.cpp /clr:safe
cl SetEx.cpp /clr:safe
cl StackAdptEx.cpp /clr:safe
cl StringColl.cpp /clr:safe
cl StringDict.cpp /clr:safe
cl VectorEx.cpp /clr:safe
